CREATE DATABASE IF NOT EXISTS nest_app;
USE nest_app;
CREATE TABLE IF NOT EXISTS nest_app.users (id int(4) AUTO_INCREMENT, name VARCHAR(20), DNI INT(9), gender VARCHAR(1), birth VARCHAR(20), PRIMARY KEY (id));

